from enum import Enum


class ActivityHoldReason(
    str,
    Enum,
):
    PENDING_MATERIAL = "PENDING_MATERIAL"
    PENDING_SPARE_PART = "PENDING_SPARE_PART"
    PENDING_PROVIDER = "PENDING_PROVIDER"
    PENDING_AUTHORIZATION = "PENDING_AUTHORIZATION"
    EQUIPMENT_IN_USE = "EQUIPMENT_IN_USE"
    OTHER = "OTHER"
